// ── /roofing — Oklahoma commercial storm lead engine ───────────────────────
// Preview dataset for the SmartX9Leads™ roofing territory page. Only the first
// VISIBLE_LEAD_COUNT rows render in the clear; the rest are blurred teasers
// that unlock after purchase.
export type RoofingLead = {
  id: string
  firstName: string
  lastName: string
  role: string
  company: string
  city: string
  zipCode: string
  email: string
  phone: string
  linkedin: string
  status: string
}

export const VISIBLE_LEAD_COUNT = 15

// Territory price shown across the /roofing page.
export const ROOFING_PRICE_MONTHLY = 34

// Web3Forms subject + sender for Oklahoma roofing territory claims.
export const ROOFING_CLAIM_SUBJECT = '🔥 New Oklahoma Roofing Territory Claim ($34/mo)'
export const ROOFING_CLAIM_FROM_NAME = 'SMART X9 — Oklahoma Roofing Territory Claim'
export const ROOFING_DEAL_LABEL = '$34/mo Oklahoma Roofing Territory License'

export const ROOFING_LEADS: RoofingLead[] = [
  {
    id: 'lead_0',
    firstName: 'Ernie',
    lastName: 'M.',
    role: 'Asset Manager',
    company: 'C-Star Management',
    city: 'Stillwater',
    zipCode: '74074',
    email: 'er****@c-s***.com',
    phone: '(405) 949-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_1',
    firstName: 'Shelbi',
    lastName: 'P.',
    role: 'General Manager',
    company: 'C-Star Management',
    city: 'Stillwater',
    zipCode: '74074',
    email: 'sh****@c-s***.com',
    phone: '(405) 949-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_5',
    firstName: 'Greg',
    lastName: 'B.',
    role: 'Managing Director',
    company: 'BANTA Property Group',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'gr****@ban***.com',
    phone: '(405) 840-****',
    linkedin: 'https://linkedin.com/in/greg-banta-53aaa813',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_6',
    firstName: 'Brian',
    lastName: 'R.',
    role: 'Real Estate Agent',
    company: 'Bailee',
    city: 'Edmond',
    zipCode: '73034',
    email: 'br****@bai***.com',
    phone: '(405) 650-****',
    linkedin: 'https://www.linkedin.com/in/brian-rush-team',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_9',
    firstName: 'Rod',
    lastName: 'B.',
    role: 'President',
    company: 'Baker First Commercial Real Estate Services',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'ba****@bak***.com',
    phone: '(405) 947-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_11',
    firstName: 'Dixie',
    lastName: 'D.',
    role: 'Brokers Sales Associate',
    company: 'Baker First Commercial Real Estate Services',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'do****@bak***.com',
    phone: '(405) 947-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_18',
    firstName: 'Gordon',
    lastName: 'W.',
    role: 'Owner',
    company: 'Hamilwood Realty',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'go****@ham***.com',
    phone: '(405) 210-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_20',
    firstName: 'Joey',
    lastName: 'C.',
    role: 'Real Estate Specialist',
    company: 'Hamilwood Realty',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'jo****@ham***.com',
    phone: '(405) 210-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_22',
    firstName: 'Bill',
    lastName: 'H.',
    role: 'Owner and Managing Broker',
    company: 'Capital Real Estate and Asset Management',
    city: 'Midwest City',
    zipCode: '73110',
    email: 'bi****@cap***.com',
    phone: '(405) 633-****',
    linkedin: 'https://www.linkedin.com/in/bill-harvey-b9141527',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_23',
    firstName: 'Lacy',
    lastName: 'B.',
    role: 'Senior Vice President',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'lb****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_24',
    firstName: 'Albert',
    lastName: 'M.',
    role: 'Manager, Property',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'am****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_25',
    firstName: 'Jason',
    lastName: 'K.',
    role: 'Commercial Properties-manager',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'jk****@cas***.com',
    phone: '(844) 326-****',
    linkedin: 'https://linkedin.com/in/jason-kennon-6a39561b',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_26',
    firstName: 'William',
    lastName: 'C.',
    role: 'Vice President, Information Technology',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'wc****@cas***.com',
    phone: '(844) 326-****',
    linkedin: 'https://www.linkedin.com/in/william-castillo-8b38b6b',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_27',
    firstName: 'Scott',
    lastName: 'C.',
    role: 'Supervisor, Property',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'sc****@cas***.com',
    phone: '(844) 326-****',
    linkedin: 'https://www.linkedin.com/in/scott-case-70456a15',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_28',
    firstName: 'Tracy',
    lastName: 'P.',
    role: 'Property Manager',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'tp****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_30',
    firstName: 'Regina',
    lastName: 'B.',
    role: 'Regional Vice President',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'rb****@cas***.com',
    phone: '(844) 326-****',
    linkedin: 'https://www.linkedin.com/in/regina-bell-9600929',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_31',
    firstName: 'Crystal',
    lastName: 'T.',
    role: 'Regional Vice President',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'ct****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_33',
    firstName: 'Kevin',
    lastName: 'W.',
    role: 'Maintenance Supervisor',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'kw****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_36',
    firstName: 'David',
    lastName: 'A.',
    role: 'Vice President & Amp. Controller',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'da****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_37',
    firstName: 'Dave',
    lastName: 'J.',
    role: 'Property Manager',
    company: 'Case & Associates Properties',
    city: 'Stillwater',
    zipCode: '74074',
    email: 'jo****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_38',
    firstName: 'Bonnie',
    lastName: 'D.',
    role: 'President-elect',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'bd****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_41',
    firstName: 'Justin',
    lastName: 'D.',
    role: 'Real Estate Analyst',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'jd****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_43',
    firstName: 'Donald',
    lastName: 'W.',
    role: 'Senior Vice President & Chief Financial Officer',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'dw****@cas***.com',
    phone: '(844) 326-****',
    linkedin: 'https://www.linkedin.com/in/don-wingfield-11482958',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_44',
    firstName: 'Clint',
    lastName: 'C.',
    role: 'Vice President Construction Management',
    company: 'Case & Associates Properties',
    city: 'Tulsa',
    zipCode: '74103',
    email: 'cc****@cas***.com',
    phone: '(844) 326-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_59',
    firstName: 'Jason',
    lastName: 'V.',
    role: 'Real Estate Agent',
    company: 'Chamberlain Realty',
    city: 'Moore',
    zipCode: '73060',
    email: 'ja****@cha***.com',
    phone: '(918) 629-****',
    linkedin: 'https://www.linkedin.com/in/jason-garder-b39a1255',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_60',
    firstName: 'Kendale',
    lastName: 'H.',
    role: 'Real Estate Specialist',
    company: 'Chamberlain Realty',
    city: 'Moore',
    zipCode: '73060',
    email: 'ke****@cha***.com',
    phone: '(918) 629-****',
    linkedin: 'https://www.linkedin.com/in/kendale-higgins-51851235',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_61',
    firstName: 'Pamela',
    lastName: 'S.',
    role: 'Real Estate Specialist',
    company: 'Chamberlain Realty',
    city: 'Moore',
    zipCode: '73060',
    email: 'pa****@cen***.com',
    phone: '(918) 629-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_62',
    firstName: 'Grant',
    lastName: 'W.',
    role: 'Broker Owner',
    company: 'Chamberlain Realty',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'gr****@cha***.com',
    phone: '(918) 629-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_64',
    firstName: 'Angie',
    lastName: 'G.',
    role: 'Broker Associate/licensed Realtor',
    company: 'Chamberlain Realty',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'an****@cha***.com',
    phone: '(918) 629-****',
    linkedin: 'https://linkedin.com/in/angie-grant-56640ba',
    status: 'Active Storm Lead',
  },
  {
    id: 'lead_65',
    firstName: 'Brandi',
    lastName: 'L.',
    role: 'Associate Broker',
    company: 'Cherrywood',
    city: 'Oklahoma City',
    zipCode: '73102',
    email: 'br****@che***.com',
    phone: '(405) 768-****',
    linkedin: '',
    status: 'Active Storm Lead',
  },
]
